name: ecommerce
description: "ShopFlow - L'expérience shopping mobile ultime. Découvrez, achetez et suivez vos commandes en toute simplicité."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.3.4
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  timeago: ^3.6.1
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.6
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  permission_handler: ^11.0.1
  http: ^1.1.0
  url_launcher: ^6.2.2
  smooth_page_indicator: ^1.1.0
  whatsapp_unilink: ^2.0.1
  shimmer: ^3.0.0
  intl: ^0.19.0
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/images/
  
  fonts:
    - family: Gilroy
      fonts:
        # - asset: assets/fonts/Gilroy-Thin.ttf
        #   weight: 100
        # - asset: assets/fonts/Gilroy-ThinItalic.ttf
        #   weight: 100
        #   style: italic
        # - asset: assets/fonts/Gilroy-UltraLight.ttf
        #   weight: 200
        # - asset: assets/fonts/Gilroy-UltraLightItalic.ttf
        #   weight: 200
        #   style: italic
        # - asset: assets/fonts/Gilroy-Light.ttf
        #   weight: 300
        - asset: assets/fonts/Gilroy-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Gilroy-Regular.ttf
          weight: 400
        - asset: assets/fonts/Gilroy-RegularItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/fonts/Gilroy-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Gilroy-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Gilroy-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700
        - asset: assets/fonts/Gilroy-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Gilroy-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Gilroy-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Gilroy-Heavy.ttf
          weight: 900
        - asset: assets/fonts/Gilroy-HeavyItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Gilroy-Black.ttf
          weight: 900
        - asset: assets/fonts/Gilroy-BlackItalic.ttf
          weight: 900
          style: italic
